#test:
#  #  hostport: httpbin.org:80
#  #  hostport: localhost:5000
#  #  uri: http://${test.hostport}
#  uri: lb://httpbin

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: example1
          uri: http://localhost:8000/
          predicates:
            - Path=/auth/**
            - Method=GET,POST


        - id: example2
          uri: http://localhost:8001/
          predicates:
            - Path=/product/**
            - Method=GET,POST


  config:
    import: "optional:configserver:"